name: PHP Composer

on: [push]

env:
  NODE_VERSION: '13.x'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Migrations
      run: |
        php yii migrate/up --interactive 0
        php yii db/seed
      
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build
      run: |
        # Build and test the project, then
        npm install
        npm run prod
        npm run css-prod

  deploy:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cleanup Directory
        run: rm -rf tutorial .git .github src && rm .gitignore package.json README.md
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@master
        env:
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
